export const paths = {
  landing: '/',
  login: '/login',
  register: '/register',
  forgotPassword: '/recuperar-contrasena',
  resetPassword: '/restablecer-contrasena',
  forbidden: '/app/403',
  app: '/app',
  dashboard: '/app',
  ventas: '/app/sales',
  productos: '/app/products',
  inventario: '/app/inventory',
  compras: '/app/purchases',
  clientes: '/app/customers',
  proveedores: '/app/suppliers',
  caja: '/app/cashier',
  configuracion: '/app/settings',
  usuarios: '/app/users',
  reportes: '/app/reports',
} as const
