export const paths = {
  landing: '/',
  login: '/login',
  register: '/register',
  forgotPassword: '/recuperar-contrasena',
  resetPassword: '/restablecer-contrasena',
  forbidden: '/app/403',
  app: '/app',
  dashboard: '/app',
  ordenesServicio: '/app/ordenes-servicio',
  clientes: '/app/customers',
  inventario: '/app/inventory',
  tecnicos: '/app/tecnicos',
  caja: '/app/cashier',
  reportes: '/app/reports',
  configuracion: '/app/settings',

  ventas: '/app/sales',
  productos: '/app/products',
  compras: '/app/purchases',
  proveedores: '/app/suppliers',
  usuarios: '/app/users',
  tiposEmpresa: '/app/admin-pos/tipos-empresa',
  empresas: '/app/admin-pos/empresas',
  administradores: '/app/admin-pos/administradores',
} as const
