ALTER TYPE "AccionAuditoria" ADD VALUE 'VIEW_RECEIPT';
ALTER TYPE "AccionAuditoria" ADD VALUE 'PRINT_RECEIPT';
ALTER TYPE "AccionAuditoria" ADD VALUE 'DOWNLOAD_RECEIPT_PDF';
ALTER TYPE "AccionAuditoria" ADD VALUE 'SHARE_RECEIPT';

