import type { AuthPermission, AuthRole } from './auth.types.js'

const roleLabels: Record<AuthRole, string> = {
  ADMIN: 'Administrador (Legacy)',
  ADMIN_EMPRESA: 'Administrador Empresa (Legacy)',
  ADMIN_BOTICA: 'Administrador de Botica',
  ADMIN_SERVICIO_TECNICO: 'Administrador Servicio Técnico',
  ADMIN_POS: 'Administrador POS (Plataforma)',
  SUPERVISOR: 'Supervisor (Legacy)',
  CAJERO: 'Cajero (Legacy)',
  ALMACEN: 'Almacén (Legacy)',
  TECNICO: 'Técnico (Legacy)',
  SUPERVISOR_BOTICA: 'Supervisor Botica',
  CAJERO_BOTICA: 'Cajero Botica',
  ALMACEN_BOTICA: 'Almacén Botica',
  SUPERVISOR_ST: 'Supervisor Servicio Técnico',
  CAJERO_ST: 'Cajero Servicio Técnico',
  TECNICO_ST: 'Técnico Servicio Técnico',
}

export const rolePermissions: Record<AuthRole, AuthPermission[]> = {
  ADMIN: [
    'dashboard.read',
    'ventas.read',
    'ventas.manage',
    'productos.read',
    'productos.manage',
    'compras.read',
    'compras.manage',
    'inventario.read',
    'inventario.manage',
    'clientes.read',
    'clientes.manage',
    'proveedores.read',
    'proveedores.manage',
    'caja.read',
    'caja.manage',
    'usuarios.read',
    'usuarios.manage',
    'sesiones.read',
    'sesiones.revoke',
    'auditoria.read',
    'reportes.read',
    'configuracion.read',
  ],
  ADMIN_EMPRESA: [
    'dashboard.read',
    'ventas.read',
    'ventas.manage',
    'productos.read',
    'productos.manage',
    'compras.read',
    'compras.manage',
    'inventario.read',
    'inventario.manage',
    'clientes.read',
    'clientes.manage',
    'proveedores.read',
    'proveedores.manage',
    'caja.read',
    'caja.manage',
    'usuarios.read',
    'usuarios.manage',
    'sesiones.read',
    'sesiones.revoke',
    'auditoria.read',
    'reportes.read',
    'configuracion.read',
  ],
  ADMIN_POS: [
    'dashboard.read',
    'tipos_empresa.manage',
    'empresas.read',
    'empresas.manage',
    'administradores.manage',
    'usuarios.read',
    'usuarios.manage',
    'sesiones.read',
    'sesiones.revoke',
    'auditoria.read',
    'reportes.read',
    'configuracion.read',
  ],
  ADMIN_BOTICA: [
    'dashboard.read',
    'ventas.read',
    'ventas.manage',
    'productos.read',
    'productos.manage',
    'compras.read',
    'compras.manage',
    'inventario.read',
    'inventario.manage',
    'clientes.read',
    'clientes.manage',
    'proveedores.read',
    'proveedores.manage',
    'caja.read',
    'caja.manage',
    'usuarios.read',
    'usuarios.manage',
    'sesiones.read',
    'sesiones.revoke',
    'auditoria.read',
    'reportes.read',
    'configuracion.read',
  ],
  SUPERVISOR_BOTICA: [
    'dashboard.read',
    'ventas.read',
    'ventas.manage',
    'productos.read',
    'compras.read',
    'inventario.read',
    'clientes.read',
    'clientes.manage',
    'proveedores.read',
    'caja.read',
    'caja.manage',
    'auditoria.read',
    'reportes.read',
  ],
  CAJERO_BOTICA: [
    'dashboard.read',
    'ventas.read',
    'ventas.manage',
    'productos.read',
    'clientes.read',
    'clientes.manage',
    'caja.read',
    'caja.manage',
  ],
  ALMACEN_BOTICA: [
    'dashboard.read',
    'productos.read',
    'compras.read',
    'inventario.read',
  ],
  ADMIN_SERVICIO_TECNICO: [
    'dashboard.read',
    'ventas.read',
    'ventas.manage',
    'productos.read',
    'productos.manage',
    'compras.read',
    'compras.manage',
    'inventario.read',
    'inventario.manage',
    'clientes.read',
    'clientes.manage',
    'proveedores.read',
    'proveedores.manage',
    'caja.read',
    'caja.manage',
    'usuarios.read',
    'usuarios.manage',
    'sesiones.read',
    'sesiones.revoke',
    'auditoria.read',
    'reportes.read',
    'configuracion.read',
    'ordenesServicio.read',
    'ordenesServicio.write',
    'ordenesServicio.cambioEstado',
    'tecnicos.read',
    'tecnicos.write',
    'equiposCliente.read',
    'equiposCliente.write',
    'presupuestosOrdenServicio.write',
    'pagosOrdenServicio.write',
    'reportesServicioTecnico.read',
    'garantiasOrdenServicio.read',
    'garantiasOrdenServicio.write',
  ],
  SUPERVISOR_ST: [
    'dashboard.read',
    'ventas.read',
    'ventas.manage',
    'productos.read',
    'compras.read',
    'inventario.read',
    'clientes.read',
    'clientes.manage',
    'proveedores.read',
    'caja.read',
    'caja.manage',
    'auditoria.read',
    'reportes.read',
    'ordenesServicio.read',
    'ordenesServicio.write',
    'ordenesServicio.cambioEstado',
    'tecnicos.read',
    'tecnicos.write',
    'equiposCliente.read',
    'equiposCliente.write',
    'presupuestosOrdenServicio.write',
    'pagosOrdenServicio.write',
    'reportesServicioTecnico.read',
    'garantiasOrdenServicio.read',
    'garantiasOrdenServicio.write',
  ],
  CAJERO_ST: [
    'dashboard.read',
    'ventas.read',
    'ventas.manage',
    'productos.read',
    'clientes.read',
    'clientes.manage',
    'caja.read',
    'caja.manage',
    'equiposCliente.read',
    'ordenesServicio.read',
    'ordenesServicio.write',
    'pagosOrdenServicio.write',
  ],
  TECNICO_ST: [
    'dashboard.read',
    'productos.read',
    'clientes.read',
    'ordenesServicio.read',
    'ordenesServicio.write',
    'ordenesServicio.cambioEstado',
    'equiposCliente.read',
    'equiposCliente.write',
    'garantiasOrdenServicio.read',
    'garantiasOrdenServicio.write',
  ],
  SUPERVISOR: [
    'dashboard.read',
    'ventas.read',
    'ventas.manage',
    'productos.read',
    'compras.read',
    'inventario.read',
    'clientes.read',
    'clientes.manage',
    'proveedores.read',
    'caja.read',
    'caja.manage',
    'auditoria.read',
    'reportes.read',
  ],
  CAJERO: [
    'dashboard.read',
    'ventas.read',
    'ventas.manage',
    'productos.read',
    'clientes.read',
    'clientes.manage',
    'caja.read',
    'caja.manage',
  ],
  ALMACEN: [
    'dashboard.read',
    'productos.read',
    'compras.read',
    'inventario.read',
  ],
  TECNICO: [
    'dashboard.read',
    'productos.read',
    'clientes.read',
    'ordenesServicio.read',
    'ordenesServicio.write',
    'ordenesServicio.cambioEstado',
    'equiposCliente.read',
    'equiposCliente.write',
    'garantiasOrdenServicio.read',
    'garantiasOrdenServicio.write',
  ],
}

const ALL_ROLE_CODES: AuthRole[] = [
  'ADMIN',
  'ADMIN_EMPRESA',
  'ADMIN_POS',
  'ADMIN_BOTICA',
  'SUPERVISOR_BOTICA',
  'CAJERO_BOTICA',
  'ALMACEN_BOTICA',
  'ADMIN_SERVICIO_TECNICO',
  'SUPERVISOR_ST',
  'CAJERO_ST',
  'TECNICO_ST',
  'SUPERVISOR',
  'CAJERO',
  'ALMACEN',
  'TECNICO',
]

export function isAuthRole(value: string): value is AuthRole {
  return ALL_ROLE_CODES.includes(value as AuthRole)
}

export function isPlatformAdminRole(role: AuthRole): boolean {
  return role === 'ADMIN_POS'
}

export function getRoleLabel(role: AuthRole) {
  return roleLabels[role]
}

export function getPermissionsForRoles(roles: AuthRole[]) {
  const expandedPermissions = roles.flatMap((role) => rolePermissions[role] ?? [])

  if (expandedPermissions.includes('*')) {
    return ['*'] as AuthPermission[]
  }

  return Array.from(new Set(expandedPermissions))
}
