import type { BadgeProps } from '@/components/ui/badge'
import type { AuthPermission, AuthRole } from '@/types/auth'

type PermissionDefinition = {
  key: Exclude<AuthPermission, '*'>
  label: string
  description: string
  module: string
}

type RoleDefinition = {
  key: AuthRole
  label: string
  description: string
  badgeVariant: NonNullable<BadgeProps['variant']>
  permissions: AuthPermission[]
}

export const permissionDefinitions: PermissionDefinition[] = [
  {
    key: 'dashboard.read',
    label: 'Ver dashboard',
    description: 'Permite acceder al panel principal y sus indicadores.',
    module: 'General',
  },
  {
    key: 'ventas.read',
    label: 'Ver ventas',
    description: 'Permite acceder al módulo de ventas.',
    module: 'Ventas',
  },
  {
    key: 'ventas.manage',
    label: 'Gestionar ventas',
    description: 'Permite realizar operaciones de venta que modifican el estado de una venta, incluyendo crear y cancelar ventas.',
    module: 'Ventas',
  },
  {
    key: 'productos.read',
    label: 'Ver productos',
    description: 'Permite acceder al catálogo de productos.',
    module: 'Productos',
  },
  {
    key: 'productos.manage',
    label: 'Gestionar productos',
    description: 'Permite crear, editar, duplicar, activar y desactivar productos del catálogo.',
    module: 'Productos',
  },
  {
    key: 'compras.read',
    label: 'Ver compras',
    description: 'Permite acceder al módulo de compras.',
    module: 'Compras',
  },
  {
    key: 'compras.manage',
    label: 'Gestionar compras',
    description: 'Permite realizar operaciones de compra que modifican su estado, incluyendo crear, editar compras y registrar recepciones.',
    module: 'Compras',
  },
  {
    key: 'inventario.read',
    label: 'Ver inventario',
    description: 'Permite revisar stock, lotes y movimientos.',
    module: 'Inventario',
  },
  {
    key: 'inventario.manage',
    label: 'Gestionar inventario',
    description: 'Permite realizar operaciones que modifican el inventario, incluyendo ajustes, transferencias y movimientos de stock.',
    module: 'Inventario',
  },
  {
    key: 'clientes.read',
    label: 'Ver clientes',
    description: 'Permite acceder al padrón de clientes.',
    module: 'Clientes',
  },
  {
    key: 'clientes.manage',
    label: 'Gestionar clientes',
    description: 'Permite crear, editar y cambiar el estado de clientes.',
    module: 'Clientes',
  },
  {
    key: 'proveedores.read',
    label: 'Ver proveedores',
    description: 'Permite acceder al padrón de proveedores.',
    module: 'Proveedores',
  },
  {
    key: 'proveedores.manage',
    label: 'Gestionar proveedores',
    description: 'Permite crear, editar y cambiar el estado de proveedores.',
    module: 'Proveedores',
  },
  {
    key: 'caja.read',
    label: 'Ver caja',
    description: 'Permite operar y consultar el módulo de caja.',
    module: 'Caja',
  },
  {
    key: 'caja.manage',
    label: 'Gestionar caja',
    description: 'Permite realizar operaciones de gestión de caja que modifican su estado, incluyendo apertura y operaciones administrativas de caja.',
    module: 'Caja',
  },
  {
    key: 'usuarios.read',
    label: 'Ver usuarios',
    description: 'Permite acceder a usuarios, roles y permisos.',
    module: 'Seguridad',
  },
  {
    key: 'usuarios.manage',
    label: 'Gestionar usuarios',
    description: 'Permite crear, editar y cambiar el estado de usuarios.',
    module: 'Seguridad',
  },
  {
    key: 'sesiones.read',
    label: 'Ver sesiones',
    description: 'Permite consultar sesiones activas y recientes.',
    module: 'Seguridad',
  },
  {
    key: 'sesiones.revoke',
    label: 'Revocar sesiones',
    description: 'Permite cerrar sesiones activas de otros usuarios.',
    module: 'Seguridad',
  },
  {
    key: 'auditoria.read',
    label: 'Ver auditoría',
    description: 'Permite consultar el historial de acciones del sistema.',
    module: 'Seguridad',
  },
  {
    key: 'reportes.read',
    label: 'Ver reportes',
    description: 'Permite acceder al módulo de reportes.',
    module: 'Reportes',
  },
  {
    key: 'configuracion.read',
    label: 'Ver configuración',
    description: 'Permite acceder a la configuración general del sistema.',
    module: 'Configuración',
  },
  {
    key: 'tipos_empresa.manage',
    label: 'Gestionar tipos de empresa',
    description: 'Permite crear, editar y activar tipos de empresa y sus módulos (plataforma).',
    module: 'Administración POS',
  },
  {
    key: 'empresas.read',
    label: 'Ver empresas',
    description: 'Permite listar y consultar la información de empresas de la plataforma.',
    module: 'Administración POS',
  },
  {
    key: 'empresas.manage',
    label: 'Gestionar empresas',
    description: 'Permite crear, editar y configurar empresas en la plataforma.',
    module: 'Administración POS',
  },
  {
    key: 'administradores.manage',
    label: 'Gestionar administradores',
    description: 'Permite asignar y administrar los administradores de empresa.',
    module: 'Administración POS',
  },
  {
    key: 'inventarioServicio.write',
    label: 'Inventario Técnico — Consumir',
    description: 'Consumir/devolver repuestos y materiales desde Orden Servicio → Kardex.',
    module: 'Inventario',
  },
  {
    key: 'reportesServicioTecnico.read',
    label: 'Reportes Servicio Técnico',
    description: 'Ver reportes/estadísticas de servicio técnico (productividad, tiempos, garantías).',
    module: 'Reportes',
  },
  {
    key: 'consumoInventarioRT.write',
    label: 'Gestionar consumo de inventario en RT',
    description: 'Permite registrar el consumo de inventario dentro de órdenes de servicio técnico.',
    module: 'Servicio Técnico',
  },
  {
    key: 'equiposCliente.read',
    label: 'Ver equipos de clientes',
    description: 'Permite consultar los equipos registrados de los clientes.',
    module: 'Servicio Técnico',
  },
  {
    key: 'equiposCliente.write',
    label: 'Crear/editar equipos de clientes',
    description: 'Permite crear y editar equipos de clientes.',
    module: 'Servicio Técnico',
  },
  {
    key: 'garantiasOrdenServicio.read',
    label: 'Ver garantías de órdenes',
    description: 'Permite consultar las garantías asociadas a órdenes de servicio técnico.',
    module: 'Servicio Técnico',
  },
  {
    key: 'garantiasOrdenServicio.write',
    label: 'Gestionar garantías de órdenes',
    description: 'Permite registrar, aprobar/rechazar y atender solicitudes de garantía asociadas a órdenes de servicio.',
    module: 'Servicio Técnico',
  },
  {
    key: 'ordenesServicio.aprobar',
    label: 'Órdenes Servicio — Aprobar Presupuesto',
    description: 'Aprobar/rechazar el presupuesto presentado al cliente.',
    module: 'Servicio Técnico',
  },
  {
    key: 'ordenesServicio.cambioEstado',
    label: 'Cambiar estado de órdenes',
    description: 'Permite cambiar el estado de las órdenes de servicio técnico.',
    module: 'Servicio Técnico',
  },
  {
    key: 'ordenesServicio.read',
    label: 'Ver órdenes de servicio',
    description: 'Permite acceder a las órdenes de servicio técnico.',
    module: 'Servicio Técnico',
  },
  {
    key: 'ordenesServicio.write',
    label: 'Crear/editar órdenes de servicio',
    description: 'Permite crear y editar órdenes de servicio técnico.',
    module: 'Servicio Técnico',
  },
  {
    key: 'pagosOrdenServicio.write',
    label: 'Gestionar pagos de órdenes',
    description: 'Permite registrar y editar pagos relacionados con órdenes de servicio técnico.',
    module: 'Servicio Técnico',
  },
  {
    key: 'presupuestosOrdenServicio.write',
    label: 'Gestionar presupuestos de órdenes',
    description: 'Permite crear y editar presupuestos para órdenes de servicio técnico.',
    module: 'Servicio Técnico',
  },
  {
    key: 'tecnicos.read',
    label: 'Ver técnicos',
    description: 'Permite listar y consultar el padrón de técnicos.',
    module: 'Servicio Técnico',
  },
  {
    key: 'tecnicos.write',
    label: 'Crear/editar técnicos',
    description: 'Permite crear y editar registros de técnicos.',
    module: 'Servicio Técnico',
  },
]

export const roleDefinitions: RoleDefinition[] = [
  {
    key: 'ADMIN_POS',
    label: 'Administrador POS',
    description: 'Gestiona la plataforma: tipos de empresa, empresas, administradores, configuración y usuarios.',
    badgeVariant: 'default',
    permissions: [
      'dashboard.read',
      'tipos_empresa.manage',
      'empresas.read',
      'empresas.manage',
      'administradores.manage',
      'usuarios.read',
      'usuarios.manage',
      'sesiones.read',
      'sesiones.revoke',
      'auditoria.read',
      'reportes.read',
      'configuracion.read',
    ],
  },
  {
    key: 'ADMIN_EMPRESA',
    label: 'Administrador de Empresa (Legacy)',
    description: 'Rol legacy (compatibilidad). Mantenido para usuarios existentes; no se usa en nuevas asignaciones.',
    badgeVariant: 'outline',
    permissions: [
      'dashboard.read',
      'ventas.read',
      'ventas.manage',
      'productos.read',
      'productos.manage',
      'compras.read',
      'compras.manage',
      'inventario.read',
      'inventario.manage',
      'clientes.read',
      'clientes.manage',
      'proveedores.read',
      'proveedores.manage',
      'caja.read',
      'caja.manage',
      'usuarios.read',
      'usuarios.manage',
      'sesiones.read',
      'sesiones.revoke',
      'auditoria.read',
      'reportes.read',
      'configuracion.read',
    ],
  },
  {
    key: 'ADMIN_BOTICA',
    label: 'Administrador de Botica',
    description: 'Administra la operación de una botica o farmacia, incluyendo usuarios, ventas, productos, compras, inventario, clientes, proveedores, caja, reportes y configuración.',
    badgeVariant: 'info',
    permissions: [
      'dashboard.read',
      'ventas.read',
      'ventas.manage',
      'productos.read',
      'productos.manage',
      'compras.read',
      'compras.manage',
      'inventario.read',
      'inventario.manage',
      'clientes.read',
      'clientes.manage',
      'proveedores.read',
      'proveedores.manage',
      'caja.read',
      'caja.manage',
      'usuarios.read',
      'usuarios.manage',
      'sesiones.read',
      'sesiones.revoke',
      'auditoria.read',
      'reportes.read',
      'configuracion.read',
    ],
  },
  {
    key: 'SUPERVISOR_BOTICA',
    label: 'Supervisor Botica',
    description: 'Supervisa la operación diaria de botica: ventas, caja, clientes, inventario, compras, auditoría y reportes.',
    badgeVariant: 'success',
    permissions: [
      'dashboard.read',
      'ventas.read',
      'ventas.manage',
      'productos.read',
      'compras.read',
      'inventario.read',
      'clientes.read',
      'clientes.manage',
      'proveedores.read',
      'caja.read',
      'caja.manage',
      'auditoria.read',
      'reportes.read',
    ],
  },
  {
    key: 'CAJERO_BOTICA',
    label: 'Cajero Botica',
    description: 'Opera el punto de venta y la caja de botica. Gestiona ventas, cobros y atención a clientes.',
    badgeVariant: 'warning',
    permissions: [
      'dashboard.read',
      'ventas.read',
      'ventas.manage',
      'productos.read',
      'clientes.read',
      'clientes.manage',
      'caja.read',
      'caja.manage',
    ],
  },
  {
    key: 'ALMACEN_BOTICA',
    label: 'Almacén Botica',
    description: 'Gestiona productos, compras e inventario en botica. No opera caja ni ventas.',
    badgeVariant: 'outline',
    permissions: [
      'dashboard.read',
      'productos.read',
      'compras.read',
      'inventario.read',
    ],
  },
  {
    key: 'ADMIN_SERVICIO_TECNICO',
    label: 'Administrador de Servicio Técnico',
    description: 'Administra la operación de servicio técnico, incluyendo usuarios, órdenes de servicio, técnicos, equipos, presupuestos, pagos, garantías y reportes.',
    badgeVariant: 'info',
    permissions: [
      'dashboard.read',
      'ventas.read',
      'ventas.manage',
      'productos.read',
      'productos.manage',
      'compras.read',
      'compras.manage',
      'inventario.read',
      'inventario.manage',
      'clientes.read',
      'clientes.manage',
      'proveedores.read',
      'proveedores.manage',
      'caja.read',
      'caja.manage',
      'usuarios.read',
      'usuarios.manage',
      'sesiones.read',
      'sesiones.revoke',
      'auditoria.read',
      'reportes.read',
      'configuracion.read',
      'ordenesServicio.read',
      'ordenesServicio.write',
      'ordenesServicio.cambioEstado',
      'tecnicos.read',
      'tecnicos.write',
      'equiposCliente.read',
      'equiposCliente.write',
      'presupuestosOrdenServicio.write',
      'pagosOrdenServicio.write',
      'reportesServicioTecnico.read',
      'garantiasOrdenServicio.read',
      'garantiasOrdenServicio.write',
    ],
  },
  {
    key: 'SUPERVISOR_ST',
    label: 'Supervisor Servicio Técnico',
    description: 'Supervisa la operación de servicio técnico: órdenes, técnicos, equipos, presupuestos, pagos, garantías, caja y reportes.',
    badgeVariant: 'success',
    permissions: [
      'dashboard.read',
      'ventas.read',
      'ventas.manage',
      'productos.read',
      'compras.read',
      'inventario.read',
      'clientes.read',
      'clientes.manage',
      'proveedores.read',
      'caja.read',
      'caja.manage',
      'auditoria.read',
      'reportes.read',
      'ordenesServicio.read',
      'ordenesServicio.write',
      'ordenesServicio.cambioEstado',
      'tecnicos.read',
      'tecnicos.write',
      'equiposCliente.read',
      'equiposCliente.write',
      'presupuestosOrdenServicio.write',
      'pagosOrdenServicio.write',
      'reportesServicioTecnico.read',
      'garantiasOrdenServicio.read',
      'garantiasOrdenServicio.write',
    ],
  },
  {
    key: 'CAJERO_ST',
    label: 'Cajero Servicio Técnico',
    description: 'Participa en recepción en servicio técnico. Gestiona ventas, caja, pagos de órdenes y consulta equipos/clientes.',
    badgeVariant: 'warning',
    permissions: [
      'dashboard.read',
      'ventas.read',
      'ventas.manage',
      'productos.read',
      'clientes.read',
      'clientes.manage',
      'caja.read',
      'caja.manage',
      'equiposCliente.read',
      'ordenesServicio.read',
      'ordenesServicio.write',
      'pagosOrdenServicio.write',
    ],
  },
  {
    key: 'TECNICO_ST',
    label: 'Técnico Servicio Técnico',
    description: 'Ejecuta órdenes de servicio, gestiona equipos de clientes y garantías. No opera caja, pagos ni ventas.',
    badgeVariant: 'info',
    permissions: [
      'dashboard.read',
      'productos.read',
      'clientes.read',
      'ordenesServicio.read',
      'ordenesServicio.write',
      'ordenesServicio.cambioEstado',
      'equiposCliente.read',
      'equiposCliente.write',
      'garantiasOrdenServicio.read',
      'garantiasOrdenServicio.write',
    ],
  },
  {
    key: 'ADMIN',
    label: 'Administrador (Legacy)',
    description: 'Rol legacy (compatibilidad). No se utiliza en nuevas asignaciones.',
    badgeVariant: 'outline',
    permissions: [
      'dashboard.read',
      'ventas.read',
      'ventas.manage',
      'productos.read',
      'productos.manage',
      'compras.read',
      'compras.manage',
      'inventario.read',
      'inventario.manage',
      'clientes.read',
      'clientes.manage',
      'proveedores.read',
      'proveedores.manage',
      'caja.read',
      'caja.manage',
      'usuarios.read',
      'usuarios.manage',
      'sesiones.read',
      'sesiones.revoke',
      'auditoria.read',
      'reportes.read',
      'configuracion.read',
    ],
  },
  {
    key: 'SUPERVISOR',
    label: 'Supervisor (Legacy)',
    description: 'Rol legacy (compatibilidad). Equivale a SUPERVISOR_BOTICA.',
    badgeVariant: 'outline',
    permissions: [
      'dashboard.read',
      'ventas.read',
      'ventas.manage',
      'productos.read',
      'compras.read',
      'inventario.read',
      'clientes.read',
      'clientes.manage',
      'proveedores.read',
      'caja.read',
      'caja.manage',
      'auditoria.read',
      'reportes.read',
    ],
  },
  {
    key: 'CAJERO',
    label: 'Cajero (Legacy)',
    description: 'Rol legacy (compatibilidad). Equivale a CAJERO_BOTICA.',
    badgeVariant: 'outline',
    permissions: [
      'dashboard.read',
      'ventas.read',
      'ventas.manage',
      'productos.read',
      'clientes.read',
      'clientes.manage',
      'caja.read',
      'caja.manage',
    ],
  },
  {
    key: 'ALMACEN',
    label: 'Almacén (Legacy)',
    description: 'Rol legacy (compatibilidad). Equivale a ALMACEN_BOTICA.',
    badgeVariant: 'outline',
    permissions: [
      'dashboard.read',
      'productos.read',
      'compras.read',
      'inventario.read',
    ],
  },
  {
    key: 'TECNICO',
    label: 'Técnico (Legacy)',
    description: 'Rol legacy (compatibilidad). Equivale a TECNICO_ST.',
    badgeVariant: 'outline',
    permissions: [
      'dashboard.read',
      'productos.read',
      'clientes.read',
      'ordenesServicio.read',
      'ordenesServicio.write',
      'ordenesServicio.cambioEstado',
      'equiposCliente.read',
      'equiposCliente.write',
      'garantiasOrdenServicio.read',
      'garantiasOrdenServicio.write',
    ],
  },
]

export const permissionDefinitionMap = Object.fromEntries(
  permissionDefinitions.map((permission) => [permission.key, permission]),
) as Record<PermissionDefinition['key'], PermissionDefinition>

export const roleDefinitionMap = Object.fromEntries(
  roleDefinitions.map((role) => [role.key, role]),
) as Record<AuthRole, RoleDefinition>

export const SERVICE_TECHNICAL_PERMISSION_CODES: ReadonlySet<AuthPermission> = new Set([
  'inventarioServicio.write',
  'reportesServicioTecnico.read',
  'consumoInventarioRT.write',
  'equiposCliente.read',
  'equiposCliente.write',
  'garantiasOrdenServicio.read',
  'garantiasOrdenServicio.write',
  'ordenesServicio.aprobar',
  'ordenesServicio.cambioEstado',
  'ordenesServicio.read',
  'ordenesServicio.write',
  'pagosOrdenServicio.write',
  'presupuestosOrdenServicio.write',
  'tecnicos.read',
  'tecnicos.write',
])

export const permissionModules = Array.from(
  new Set(permissionDefinitions.map((permission) => permission.module)),
)

export function getDefaultPermissionsForRoles(roles: AuthRole[]) {
  const expandedPermissions = roles.flatMap(
    (role) => roleDefinitionMap[role]?.permissions ?? [],
  )

  if (expandedPermissions.includes('*')) {
    return ['*'] as AuthPermission[]
  }

  return Array.from(new Set(expandedPermissions))
}
